name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild -scheme redeye \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO
